-- src/main/resources/db/migration/V1__init.sql
-- Initial Baseline: All core tables and indexes for PostgreSQL

-- Enable extension for trgm-based LIKE search optimization
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 1) users
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(320) NOT NULL,
    name          VARCHAR(100) NOT NULL,
    role          VARCHAR(10)  NOT NULL DEFAULT 'USER',
    status        VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE',
    last_login_at TIMESTAMP(6) WITH TIME ZONE,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'SUSPENDED'))
);

-- 2) folders
CREATE TABLE folders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT NOT NULL,
    parent_id  BIGINT,
    name       VARCHAR(120) NOT NULL,
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_folders_owner  FOREIGN KEY (owner_id) REFERENCES users(id),
    CONSTRAINT fk_folders_parent FOREIGN KEY (parent_id) REFERENCES folders(id)
);

-- 3) notes
CREATE TABLE notes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id      BIGINT NOT NULL,
    folder_id      BIGINT,
    title          VARCHAR(200) NOT NULL,
    content        TEXT NOT NULL,
    visibility     VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    ai_collectable BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at     TIMESTAMP(6) WITH TIME ZONE,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notes_author FOREIGN KEY (author_id) REFERENCES users(id),
    CONSTRAINT fk_notes_folder FOREIGN KEY (folder_id) REFERENCES folders(id),
    CONSTRAINT chk_notes_visibility CHECK (visibility IN ('PUBLIC', 'PRIVATE', 'UNLISTED'))
);

-- 4) user_oauth_accounts
CREATE TABLE user_oauth_accounts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    provider         VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(190) NOT NULL,
    email            VARCHAR(320),
    avatar_url       VARCHAR(500),
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_oauth_provider_user UNIQUE (provider, provider_user_id),
    CONSTRAINT fk_user_oauth_accounts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_user_oauth_provider     CHECK (provider IN ('GOOGLE', 'KAKAO'))
);

-- 5) user_password_credentials (Shared Primary Key: PK = FK)
CREATE TABLE user_password_credentials (
    user_id             BIGINT PRIMARY KEY,
    login_id            VARCHAR(320) NOT NULL,
    password_hash       VARCHAR(255) NOT NULL,
    password_changed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_user_password_login_id        UNIQUE (login_id),
    CONSTRAINT fk_user_password_credentials_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- === Indexes ===

-- Folders
CREATE INDEX idx_folders_owner_deleted_name ON folders (owner_id, deleted_at, name);
CREATE INDEX idx_folders_owner_parent_deleted_name ON folders (owner_id, parent_id, deleted_at, name);

-- Notes (Query path optimization)
CREATE INDEX idx_notes_author_active_created ON notes (author_id, created_at DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_notes_visibility_active_created ON notes (visibility, created_at DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_notes_folder_active ON notes (folder_id) WHERE deleted_at IS NULL;

-- Notes (Keyword search optimization using pg_trgm)
CREATE INDEX idx_notes_title_trgm   ON notes USING GIN (lower(title)   gin_trgm_ops);
CREATE INDEX idx_notes_content_trgm ON notes USING GIN (lower(content) gin_trgm_ops);

-- Auth
CREATE INDEX idx_user_oauth_accounts_user_id ON user_oauth_accounts (user_id);
