-- 6) activity_events
CREATE TABLE activity_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    note_id       BIGINT NOT NULL,
    type          VARCHAR(30) NOT NULL,
    activity_date DATE NOT NULL,
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_activity_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_activity_events_note FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE,
    CONSTRAINT chk_activity_events_type CHECK (type IN ('NOTE_CREATED', 'NOTE_UPDATED'))
);

-- Activity dashboard query path optimization
CREATE INDEX idx_activity_events_user_activity_date ON activity_events (user_id, activity_date);
CREATE INDEX idx_activity_events_note_id ON activity_events (note_id);
