CREATE TABLE note_images
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     UUID         NOT NULL,
    note_id       BIGINT       NOT NULL,
    uploader_id   BIGINT       NOT NULL,
    storage_key   VARCHAR(512) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    content_type  VARCHAR(100) NOT NULL,
    file_size     BIGINT       NOT NULL,
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at    TIMESTAMP(6) WITHOUT TIME ZONE,

    CONSTRAINT uq_note_images_public_id UNIQUE (public_id),
    CONSTRAINT uq_note_images_storage_key UNIQUE (storage_key),
    CONSTRAINT fk_note_images_note FOREIGN KEY (note_id) REFERENCES notes (id),
    CONSTRAINT fk_note_images_uploader FOREIGN KEY (uploader_id) REFERENCES users (id),
    CONSTRAINT chk_note_images_file_size_positive CHECK ( file_size > 0 )
);

CREATE INDEX idx_note_images_note_active
    ON note_images (note_id) WHERE deleted_at IS NULL;

CREATE INDEX idx_note_images_uploader_active
    ON note_images (uploader_id) WHERE deleted_at IS NULL;
