-- 4) ai_note_indexes
CREATE TABLE ai_note_indexes
(
    note_id           BIGINT PRIMARY KEY,
    author_id         BIGINT      NOT NULL,
    status            VARCHAR(20) NOT NULL,
    attempt_count     INT         NOT NULL DEFAULT 0,
    last_requested_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_processed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    indexed_at        TIMESTAMP(6) WITHOUT TIME ZONE,
    last_error        VARCHAR(1000),
    CONSTRAINT fk_ai_note_indexes_note
        FOREIGN KEY (note_id) REFERENCES notes (id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_note_indexes_author
        FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_ai_note_indexes_status
        CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'REMOVED'))
);

-- 5) ai_note_chunks
CREATE TABLE ai_note_chunks
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id           BIGINT       NOT NULL,
    author_id         BIGINT       NOT NULL,
    chunk_order       INT          NOT NULL,
    title             VARCHAR(200) NOT NULL,
    content_chunk     TEXT         NOT NULL,
    source_updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    indexed_at        TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_ai_note_chunks_note
        FOREIGN KEY (note_id) REFERENCES notes (id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_note_chunks_author
        FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_ai_note_chunks_note_order
        UNIQUE (note_id, chunk_order)
);

CREATE INDEX idx_ai_note_indexes_author_status
    ON ai_note_indexes (author_id, status);

CREATE INDEX idx_ai_note_chunks_author_note
    ON ai_note_chunks (author_id, note_id, chunk_order);
